"""Pluggable inference backends behind one tiny interface.

The point of this file is that ``yolo_detector_node`` never imports torch,
onnxruntime or tensorrt directly. It asks for a backend by name and gets an
object with ``infer(bgr_image) -> (boxes, timings)``. That buys three things:

* You can develop on the Mac with the ``ultralytics`` backend and deploy to the
  Jetson with ``tensorrt``, changing one launch argument.
* The optimization report's latency table is generated by running the *same*
  benchmark loop against each backend, so the numbers are genuinely comparable.
* If the TensorRT engine fails to load on exam day, the launch file falls back
  to onnxruntime and the demo still runs, slower.

Boxes are returned as a list of (x, y, w, h, score, label) in the coordinate
space of the *input image*, already rescaled out of letterbox space.
"""

import time

import numpy as np


class BackendError(RuntimeError):
    pass


class BaseBackend:
    name = "base"

    def __init__(self, model_path, imgsz=640, conf=0.35, iou=0.45, classes=(0,)):
        self.model_path = model_path
        self.imgsz = int(imgsz)
        self.conf = float(conf)
        self.iou = float(iou)
        self.classes = tuple(classes)
        self.model_name = str(model_path).split("/")[-1]

    def warmup(self, iterations=10):
        dummy = np.zeros((self.imgsz, self.imgsz, 3), dtype=np.uint8)
        for _ in range(iterations):
            self.infer(dummy)

    def infer(self, bgr):
        raise NotImplementedError


# ----------------------------------------------------------------------
# Shared pre/post-processing so every backend is measured on equal terms.
# ----------------------------------------------------------------------

def letterbox(bgr, new_size, colour=114):
    import cv2
    h, w = bgr.shape[:2]
    r = min(new_size / h, new_size / w)
    nh, nw = int(round(h * r)), int(round(w * r))
    resized = cv2.resize(bgr, (nw, nh), interpolation=cv2.INTER_LINEAR)
    canvas = np.full((new_size, new_size, 3), colour, dtype=np.uint8)
    top = (new_size - nh) // 2
    left = (new_size - nw) // 2
    canvas[top:top + nh, left:left + nw] = resized
    return canvas, r, left, top


def nms(boxes, scores, iou_threshold):
    """Plain-numpy NMS. boxes are xyxy."""
    if len(boxes) == 0:
        return []
    boxes = np.asarray(boxes, dtype=np.float32)
    scores = np.asarray(scores, dtype=np.float32)
    x1, y1, x2, y2 = boxes[:, 0], boxes[:, 1], boxes[:, 2], boxes[:, 3]
    areas = (x2 - x1).clip(0) * (y2 - y1).clip(0)
    order = scores.argsort()[::-1]
    keep = []
    while order.size > 0:
        i = order[0]
        keep.append(int(i))
        if order.size == 1:
            break
        xx1 = np.maximum(x1[i], x1[order[1:]])
        yy1 = np.maximum(y1[i], y1[order[1:]])
        xx2 = np.minimum(x2[i], x2[order[1:]])
        yy2 = np.minimum(y2[i], y2[order[1:]])
        inter = (xx2 - xx1).clip(0) * (yy2 - yy1).clip(0)
        iou = inter / (areas[i] + areas[order[1:]] - inter + 1e-9)
        order = order[1:][iou <= iou_threshold]
    return keep


def decode_yolo_output(raw, r, pad_left, pad_top, conf, iou, classes, img_shape):
    """Decode a YOLOv8/YOLO11 raw head: (1, 4+nc, num_anchors)."""
    pred = raw[0] if raw.ndim == 3 else raw
    if pred.shape[0] < pred.shape[1]:
        pred = pred.T  # -> (num_anchors, 4+nc)

    xywh = pred[:, :4]
    cls_scores = pred[:, 4:]
    class_ids = cls_scores.argmax(axis=1)
    scores = cls_scores.max(axis=1)

    mask = scores >= conf
    if classes:
        mask &= np.isin(class_ids, classes)
    if not mask.any():
        return []

    xywh = xywh[mask]
    scores = scores[mask]
    class_ids = class_ids[mask]

    cx, cy, bw, bh = xywh[:, 0], xywh[:, 1], xywh[:, 2], xywh[:, 3]
    x1 = (cx - bw / 2 - pad_left) / r
    y1 = (cy - bh / 2 - pad_top) / r
    x2 = (cx + bw / 2 - pad_left) / r
    y2 = (cy + bh / 2 - pad_top) / r

    H, W = img_shape[:2]
    x1 = x1.clip(0, W - 1)
    y1 = y1.clip(0, H - 1)
    x2 = x2.clip(0, W - 1)
    y2 = y2.clip(0, H - 1)

    boxes_xyxy = np.stack([x1, y1, x2, y2], axis=1)
    keep = nms(boxes_xyxy, scores, iou)

    out = []
    for i in keep:
        out.append((int(x1[i]), int(y1[i]),
                    int(x2[i] - x1[i]), int(y2[i] - y1[i]),
                    float(scores[i]), "person" if class_ids[i] == 0 else str(int(class_ids[i]))))
    return out


# ----------------------------------------------------------------------


class UltralyticsBackend(BaseBackend):
    """Reference implementation. Correct, portable, and too slow for the rubric.

    This is the *baseline* row in the optimization report: it runs on the Mac
    (MPS) and on the Jetson (CUDA via torch) and gives the accuracy ceiling every
    optimized variant is compared against.
    """

    name = "ultralytics"

    def __init__(self, *args, device="cpu", **kwargs):
        super().__init__(*args, **kwargs)
        try:
            from ultralytics import YOLO
        except ImportError as exc:
            raise BackendError("ultralytics not installed: %s" % exc)
        self.device = device
        self.model = YOLO(self.model_path)

    def infer(self, bgr):
        t0 = time.perf_counter()
        res = self.model.predict(bgr, imgsz=self.imgsz, conf=self.conf,
                                 iou=self.iou, classes=list(self.classes),
                                 device=self.device, verbose=False)[0]
        t1 = time.perf_counter()
        boxes = []
        for b in res.boxes:
            x1, y1, x2, y2 = [float(v) for v in b.xyxy[0].tolist()]
            boxes.append((int(x1), int(y1), int(x2 - x1), int(y2 - y1),
                          float(b.conf[0]), "person"))
        speed = getattr(res, "speed", {}) or {}
        timings = {
            "preprocess_ms": float(speed.get("preprocess", 0.0)),
            "inference_ms": float(speed.get("inference", (t1 - t0) * 1000.0)),
            "postprocess_ms": float(speed.get("postprocess", 0.0)),
        }
        return boxes, timings


class OnnxRuntimeBackend(BaseBackend):
    """The portable middle rung, and the exam-day safety net.

    Runs the exported .onnx on CPU or CUDA. Slower than TensorRT but it will
    load on any machine, which makes it the fallback if the .engine is stale
    (TensorRT engines are tied to the exact TRT/driver version that built them).
    """

    name = "onnxruntime"

    def __init__(self, *args, providers=None, **kwargs):
        super().__init__(*args, **kwargs)
        try:
            import onnxruntime as ort
        except ImportError as exc:
            raise BackendError("onnxruntime not installed: %s" % exc)
        providers = providers or ["CUDAExecutionProvider", "CPUExecutionProvider"]
        available = ort.get_available_providers()
        providers = [p for p in providers if p in available] or ["CPUExecutionProvider"]
        self.session = ort.InferenceSession(self.model_path, providers=providers)
        self.input_name = self.session.get_inputs()[0].name
        self.providers = providers

    def infer(self, bgr):
        t0 = time.perf_counter()
        canvas, r, pl, pt = letterbox(bgr, self.imgsz)
        blob = canvas[:, :, ::-1].transpose(2, 0, 1)[None].astype(np.float32) / 255.0
        blob = np.ascontiguousarray(blob)
        t1 = time.perf_counter()
        raw = self.session.run(None, {self.input_name: blob})[0]
        t2 = time.perf_counter()
        boxes = decode_yolo_output(np.asarray(raw), r, pl, pt, self.conf,
                                   self.iou, self.classes, bgr.shape)
        t3 = time.perf_counter()
        return boxes, {
            "preprocess_ms": (t1 - t0) * 1000.0,
            "inference_ms": (t2 - t1) * 1000.0,
            "postprocess_ms": (t3 - t2) * 1000.0,
        }


class TensorRTBackend(BaseBackend):
    """The number that goes in the report.

    Loads a serialized .engine built by ``trtexec`` **on the Jetson itself**.
    Engines are not portable across TensorRT versions or GPU architectures, so
    never try to build this on the Mac -- see training/build_engine_on_jetson.sh.
    """

    name = "tensorrt"

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        try:
            import tensorrt as trt
            import pycuda.driver as cuda
            import pycuda.autoinit  # noqa: F401  (creates the CUDA context)
        except ImportError as exc:
            raise BackendError("tensorrt/pycuda not available: %s" % exc)

        self.trt = trt
        self.cuda = cuda
        logger = trt.Logger(trt.Logger.WARNING)
        with open(self.model_path, "rb") as f, trt.Runtime(logger) as runtime:
            self.engine = runtime.deserialize_cuda_engine(f.read())
        if self.engine is None:
            raise BackendError("failed to deserialize %s -- rebuild the engine "
                               "on this device" % self.model_path)
        self.context = self.engine.create_execution_context()
        self.stream = cuda.Stream()

        self.bindings = []
        self.host_buffers = {}
        self.device_buffers = {}
        for idx in range(self.engine.num_bindings):
            name = self.engine.get_binding_name(idx)
            shape = tuple(self.engine.get_binding_shape(idx))
            dtype = trt.nptype(self.engine.get_binding_dtype(idx))
            size = int(np.prod(shape))
            host = cuda.pagelocked_empty(size, dtype)
            device = cuda.mem_alloc(host.nbytes)
            self.bindings.append(int(device))
            self.host_buffers[name] = (host, shape)
            self.device_buffers[name] = device
            if self.engine.binding_is_input(idx):
                self.input_name = name
                self.input_shape = shape
            else:
                self.output_name = name
                self.output_shape = shape

    def infer(self, bgr):
        cuda = self.cuda
        t0 = time.perf_counter()
        canvas, r, pl, pt = letterbox(bgr, self.imgsz)
        blob = canvas[:, :, ::-1].transpose(2, 0, 1)[None].astype(np.float32) / 255.0
        host_in, _ = self.host_buffers[self.input_name]
        np.copyto(host_in, blob.ravel())
        t1 = time.perf_counter()

        cuda.memcpy_htod_async(self.device_buffers[self.input_name], host_in, self.stream)
        self.context.execute_async_v2(bindings=self.bindings,
                                      stream_handle=self.stream.handle)
        host_out, out_shape = self.host_buffers[self.output_name]
        cuda.memcpy_dtoh_async(host_out, self.device_buffers[self.output_name], self.stream)
        self.stream.synchronize()
        t2 = time.perf_counter()

        raw = host_out.reshape(out_shape)
        boxes = decode_yolo_output(raw, r, pl, pt, self.conf, self.iou,
                                   self.classes, bgr.shape)
        t3 = time.perf_counter()
        return boxes, {
            "preprocess_ms": (t1 - t0) * 1000.0,
            "inference_ms": (t2 - t1) * 1000.0,
            "postprocess_ms": (t3 - t2) * 1000.0,
        }


BACKENDS = {
    "ultralytics": UltralyticsBackend,
    "onnxruntime": OnnxRuntimeBackend,
    "tensorrt": TensorRTBackend,
}


def build_backend(name, model_path, **kwargs):
    if name not in BACKENDS:
        raise BackendError("unknown backend %r (have: %s)"
                           % (name, ", ".join(sorted(BACKENDS))))
    return BACKENDS[name](model_path, **kwargs)
