#!/usr/bin/env python3
"""Pre-label the frames you pulled off the robot, then correct by hand.

    python3 training/autolabel.py --images data/frames --out data/dataset \
        --teacher yolov8x.pt --conf 0.25 --val-split 0.2

Why a big teacher model and not just "use COCO YOLO at runtime": the whole
point of the fine-tune is the domain gap. A camera 20 cm off a classroom floor
sees thighs, chair legs, and torsos cropped at the shoulders. COCO's person
class is dominated by full-body pedestrians shot from 1.5 m. yolov8x still
finds most of these frames' people because it has capacity to spare, and it
runs offline on your Mac where 2 FPS is fine -- so it makes a decent first pass
that you then *fix*, which is far faster than labelling from scratch.

Budget roughly: 300-600 frames auto-labelled, 45 minutes of correction. Fix the
misses (people it missed entirely) before you fix the boxes -- a missing label
teaches the student that a person is background, which is much worse than a
box that is 15 px too wide.

Correct the output in any YOLO-format tool: labelImg, Label Studio, CVAT, or
Roboflow (drag the folder in, it reads YOLO txt directly).
"""

import argparse
import os
import random
import shutil
import sys


DATA_YAML = """# Auto-generated by training/autolabel.py
path: {root}
train: images/train
val: images/val
names:
  0: person
"""


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--images", required=True, help="folder of .jpg frames from the robot")
    ap.add_argument("--out", default="data/dataset")
    ap.add_argument("--teacher", default="yolov8x.pt")
    ap.add_argument("--conf", type=float, default=0.25,
                    help="low on purpose: recall matters more than precision here, "
                         "because deleting a wrong box is faster than drawing a missing one")
    ap.add_argument("--imgsz", type=int, default=960,
                    help="run the teacher at high res even though the student will be "
                         "smaller -- you want the teacher's best guess, not a fast one")
    ap.add_argument("--val-split", type=float, default=0.2)
    ap.add_argument("--device", default="mps",
                    help="mps on Apple silicon, cuda:0 on an NVIDIA box, cpu everywhere")
    ap.add_argument("--seed", type=int, default=0)
    args = ap.parse_args()

    try:
        from ultralytics import YOLO
    except ImportError:
        sys.exit("pip install ultralytics")

    frames = sorted(f for f in os.listdir(args.images)
                    if f.lower().endswith((".jpg", ".jpeg", ".png")))
    if not frames:
        sys.exit("no images in %s" % args.images)

    random.seed(args.seed)
    random.shuffle(frames)
    n_val = max(1, int(len(frames) * args.val_split))
    split_of = {f: ("val" if i < n_val else "train") for i, f in enumerate(frames)}

    root = os.path.abspath(args.out)
    for split in ("train", "val"):
        os.makedirs(os.path.join(root, "images", split), exist_ok=True)
        os.makedirs(os.path.join(root, "labels", split), exist_ok=True)

    model = YOLO(args.teacher)
    print("labelling %d frames with %s ..." % (len(frames), args.teacher))

    boxes_total = empty_frames = 0
    for i, fname in enumerate(frames, 1):
        src = os.path.join(args.images, fname)
        split = split_of[fname]
        res = model.predict(src, imgsz=args.imgsz, conf=args.conf, classes=[0],
                            device=args.device, verbose=False)[0]

        shutil.copy2(src, os.path.join(root, "images", split, fname))
        stem = os.path.splitext(fname)[0]
        label_path = os.path.join(root, "labels", split, stem + ".txt")

        lines = []
        for b in res.boxes:
            # ultralytics gives normalised xywh directly, which is exactly the
            # YOLO label format -- no conversion arithmetic to get wrong.
            x, y, w, h = [float(v) for v in b.xywhn[0].tolist()]
            lines.append("0 %.6f %.6f %.6f %.6f" % (x, y, w, h))
        boxes_total += len(lines)
        if not lines:
            empty_frames += 1
        with open(label_path, "w") as fh:
            fh.write("\n".join(lines) + ("\n" if lines else ""))

        if i % 50 == 0 or i == len(frames):
            print("  %d/%d" % (i, len(frames)))

    with open(os.path.join(root, "data.yaml"), "w") as fh:
        fh.write(DATA_YAML.format(root=root))

    print("""
done.
  dataset      {root}
  frames       {n} ({tr} train / {va} val)
  boxes        {boxes}
  empty frames {empty}   <- check these first, they are usually misses

NOW GO AND CORRECT THE LABELS. Seriously. Open {root}/images/train in
labelImg or Label Studio and fix the misses. The single biggest determinant of
your final mAP is whether the people the teacher missed got labelled.

Then:
  python3 training/finetune.py --data {root}/data.yaml
""".format(root=root, n=len(frames), tr=len(frames) - n_val, va=n_val,
           boxes=boxes_total, empty=empty_frames))


if __name__ == "__main__":
    main()
